Develop:
  ServicePort: 6789
  Level: "dev"
  WithHandleMethodNotAllowed: true
  Domain: "api-boe.demo.net"

Product:
  ServicePort: 6790
  Level: "pro"
  WithHandleMethodNotAllowed: true
  Domain: "api.demo.net"

MysqlDevelop:
  MysqlUrl: "root:root123456@tcp(127.0.0.1:3306)/gfw?charset=utf8&parseTime=true&loc=Asia%2FChongqing"
  MaxOpenConn: 20
  MaxIdleConn: 10
  MaxConnLifeTime: 100

MysqlProduct:
  MysqlUrl: "root:root123456@tcp(127.0.0.1:3306)/gfw?charset=utf8&parseTime=true&loc=Asia%2FChongqing"
  MaxOpenConn: 20
  MaxIdleConn: 10
  MaxConnLiftTime: 100

RedisDevelop:
  Addr: "127.0.0.1:6379"
  MaxActive: 100
  PoolSize: 50
  MaxRetries: 10
  Db: 0

RedisProduct:
  Addr: "127.0.0.1:6379"
  MaxActive: 100
  PoolSize: 50
  MaxRetries: 10
  Db: 0

GameConfigDevelop:
  DefaultCurrency: usd

GameConfigProduct:
  DefaultCurrency: usd
